//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuisenessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSetting
    {
        public int MailSettingsId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string SMTP { get; set; }
        public string SMTPPort { get; set; }
        public string Pop3 { get; set; }
        public string Pop3Port { get; set; }
        public bool EnableSSL { get; set; }
        public string Imap { get; set; }
        public string ImapPort { get; set; }
    }
}
