//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuisenessLogicLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MySmtpEntities : DbContext
    {
        public MySmtpEntities()
            : base("name=MySmtpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MailSetting> MailSettings { get; set; }
        public virtual DbSet<RecipientList> RecipientLists { get; set; }
        public virtual DbSet<RecipientListsRelation> RecipientListsRelations { get; set; }
        public virtual DbSet<Recipient> Recipients { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
    
        public virtual ObjectResult<sp_getRecipientsByListId_Result> sp_getRecipientsByListId(Nullable<int> rlId)
        {
            var rlIdParameter = rlId.HasValue ?
                new ObjectParameter("rlId", rlId) :
                new ObjectParameter("rlId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getRecipientsByListId_Result>("sp_getRecipientsByListId", rlIdParameter);
        }
    }
}
