//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuisenessLogicLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySmtpEntities : DbContext
    {
        public MySmtpEntities()
            : base("name=MySmtpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MailSetting> MailSettings { get; set; }
        public virtual DbSet<RecipientList> RecipientLists { get; set; }
        public virtual DbSet<RecipientListsRelation> RecipientListsRelations { get; set; }
        public virtual DbSet<Recipient> Recipients { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
    }
}
