//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuisenessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipientListsRelation
    {
        public int Id { get; set; }
        public int rlId { get; set; }
        public int rId { get; set; }
    
        public virtual RecipientList RecipientList { get; set; }
        public virtual Recipient Recipient { get; set; }
    }
}
