//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuisenessLogicLayer
{
    using System;
    
    public partial class sp_getRecipientsByListIdResult
    {
        public int RecipientId { get; set; }
        public string Email { get; set; }
        public int Selected { get; set; }
    }
}
